// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Estriper0/EventService/internal/models"
	event "github.com/Estriper0/protobuf/gen/event"
	gomock "github.com/golang/mock/gomock"
)

// MockIEventService is a mock of IEventService interface.
type MockIEventService struct {
	ctrl     *gomock.Controller
	recorder *MockIEventServiceMockRecorder
}

// MockIEventServiceMockRecorder is the mock recorder for MockIEventService.
type MockIEventServiceMockRecorder struct {
	mock *MockIEventService
}

// NewMockIEventService creates a new mock instance.
func NewMockIEventService(ctrl *gomock.Controller) *MockIEventService {
	mock := &MockIEventService{ctrl: ctrl}
	mock.recorder = &MockIEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEventService) EXPECT() *MockIEventServiceMockRecorder {
	return m.recorder
}

// CancellRegister mocks base method.
func (m *MockIEventService) CancellRegister(ctx context.Context, user_id string, event_id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancellRegister", ctx, user_id, event_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancellRegister indicates an expected call of CancellRegister.
func (mr *MockIEventServiceMockRecorder) CancellRegister(ctx, user_id, event_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancellRegister", reflect.TypeOf((*MockIEventService)(nil).CancellRegister), ctx, user_id, event_id)
}

// Create mocks base method.
func (m *MockIEventService) Create(ctx context.Context, event *models.EventCreateRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIEventServiceMockRecorder) Create(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIEventService)(nil).Create), ctx, event)
}

// DeleteById mocks base method.
func (m *MockIEventService) DeleteById(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockIEventServiceMockRecorder) DeleteById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockIEventService)(nil).DeleteById), ctx, id)
}

// GetAll mocks base method.
func (m *MockIEventService) GetAll(ctx context.Context) ([]*models.EventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*models.EventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIEventServiceMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIEventService)(nil).GetAll), ctx)
}

// GetAllByCreator mocks base method.
func (m *MockIEventService) GetAllByCreator(ctx context.Context, creator string) ([]*models.EventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByCreator", ctx, creator)
	ret0, _ := ret[0].([]*models.EventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByCreator indicates an expected call of GetAllByCreator.
func (mr *MockIEventServiceMockRecorder) GetAllByCreator(ctx, creator interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByCreator", reflect.TypeOf((*MockIEventService)(nil).GetAllByCreator), ctx, creator)
}

// GetAllByStatus mocks base method.
func (m *MockIEventService) GetAllByStatus(ctx context.Context, status string) ([]*models.EventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByStatus", ctx, status)
	ret0, _ := ret[0].([]*models.EventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByStatus indicates an expected call of GetAllByStatus.
func (mr *MockIEventServiceMockRecorder) GetAllByStatus(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByStatus", reflect.TypeOf((*MockIEventService)(nil).GetAllByStatus), ctx, status)
}

// GetAllByUser mocks base method.
func (m *MockIEventService) GetAllByUser(ctx context.Context, user_id string) (*event.GetAllByUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByUser", ctx, user_id)
	ret0, _ := ret[0].(*event.GetAllByUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByUser indicates an expected call of GetAllByUser.
func (mr *MockIEventServiceMockRecorder) GetAllByUser(ctx, user_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByUser", reflect.TypeOf((*MockIEventService)(nil).GetAllByUser), ctx, user_id)
}

// GetAllUsersByEvent mocks base method.
func (m *MockIEventService) GetAllUsersByEvent(ctx context.Context, event_id int) (*event.GetAllUsersByEventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsersByEvent", ctx, event_id)
	ret0, _ := ret[0].(*event.GetAllUsersByEventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsersByEvent indicates an expected call of GetAllUsersByEvent.
func (mr *MockIEventServiceMockRecorder) GetAllUsersByEvent(ctx, event_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsersByEvent", reflect.TypeOf((*MockIEventService)(nil).GetAllUsersByEvent), ctx, event_id)
}

// GetById mocks base method.
func (m *MockIEventService) GetById(ctx context.Context, id int) (*models.EventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*models.EventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIEventServiceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIEventService)(nil).GetById), ctx, id)
}

// Register mocks base method.
func (m *MockIEventService) Register(ctx context.Context, user_id string, event_id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, user_id, event_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockIEventServiceMockRecorder) Register(ctx, user_id, event_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIEventService)(nil).Register), ctx, user_id, event_id)
}

// Update mocks base method.
func (m *MockIEventService) Update(ctx context.Context, event *models.EventUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIEventServiceMockRecorder) Update(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIEventService)(nil).Update), ctx, event)
}
